######################遊戲基本設定######################

# 螢幕設定
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60

# 顏色定義
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)
PURPLE = (128, 0, 128)
CYAN = (0, 255, 255)
GRAY = (128, 128, 128)
DARK_GRAY = (64, 64, 64)

# 關卡場景顏色
LAVA_COLOR = (255, 80, 0)  # 橘紅色熔岩
WATER_COLOR = (0, 150, 255)  # 藍色水流
WIND_COLOR = (200, 200, 200)  # 灰白色風暴
PLATFORM_COLOR = (100, 50, 0)  # 棕色平台

# UI 相關設定
SCORE_COLOR = WHITE
SCORE_FONT_SIZE = 24
PLATFORM_HEIGHT = 20

######################玩家設定######################

# 玩家基本屬性
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 60
PLAYER_COLOR = BLUE
PLAYER_SPEED = 8
PLAYER_JUMP_STRENGTH = -18
PLAYER_MAX_HEALTH = 100

# 跑酷相關設定
GRAVITY = 1.2
MAX_FALL_SPEED = 20
WALL_JUMP_STRENGTH = -15
WALL_JUMP_PUSH = 12
DOUBLE_JUMP_STRENGTH = -12

######################武器與子彈設定######################

# 槍械基本設定
GUN_RANGE = 300
MELEE_RANGE = 80
BULLET_SPEED = 15
BULLET_SIZE = 8
FIRE_RATE = 0.3  # 發射間隔（秒）

# 子彈屬性顏色
WATER_BULLET_COLOR = CYAN
ICE_BULLET_COLOR = WHITE
THUNDER_BULLET_COLOR = YELLOW
FIRE_BULLET_COLOR = RED

# 子彈屬性傷害
WATER_DAMAGE = 25
ICE_DAMAGE = 20
THUNDER_DAMAGE = 30
FIRE_DAMAGE = 35

# 近戰攻擊設定
MELEE_DAMAGE = 40
MELEE_KNOCKBACK = 100

######################怪物設定######################

# 岩漿怪
LAVA_MONSTER_WIDTH = 50
LAVA_MONSTER_HEIGHT = 50
LAVA_MONSTER_COLOR = RED
LAVA_MONSTER_SPEED = 3
LAVA_MONSTER_HEALTH = 80
LAVA_MONSTER_DAMAGE = 30

# 水怪
WATER_MONSTER_WIDTH = 45
WATER_MONSTER_HEIGHT = 45
WATER_MONSTER_COLOR = BLUE
WATER_MONSTER_SPEED = 5
WATER_MONSTER_HEALTH = 60
WATER_MONSTER_DAMAGE = 25

# 龍捲風怪
TORNADO_MONSTER_WIDTH = 40
TORNADO_MONSTER_HEIGHT = 70
TORNADO_MONSTER_COLOR = GRAY
TORNADO_MONSTER_SPEED = 8
TORNADO_MONSTER_HEALTH = 40
TORNADO_MONSTER_DAMAGE = 35

######################Boss設定######################

# 熔岩龍捲怪 Boss
LAVA_TORNADO_BOSS_WIDTH = 120
LAVA_TORNADO_BOSS_HEIGHT = 150
LAVA_TORNADO_BOSS_COLOR = ORANGE
LAVA_TORNADO_BOSS_SPEED = 4
LAVA_TORNADO_BOSS_HEALTH = 500
LAVA_TORNADO_BOSS_DAMAGE = 50

# 海嘯巨獸 Boss
TSUNAMI_BOSS_WIDTH = 150
TSUNAMI_BOSS_HEIGHT = 120
TSUNAMI_BOSS_COLOR = DARK_GRAY
TSUNAMI_BOSS_SPEED = 3
TSUNAMI_BOSS_HEALTH = 600
TSUNAMI_BOSS_DAMAGE = 60

######################屬性剋制設定######################

# 剋制倍率
WEAKNESS_MULTIPLIER = 2.0  # 弱點攻擊傷害倍率
RESISTANCE_MULTIPLIER = 0.5  # 抗性攻擊傷害倍率
NORMAL_MULTIPLIER = 1.0  # 一般攻擊傷害倍率

# 狀態效果持續時間（秒）
SLOW_EFFECT_DURATION = 3.0
PARALYSIS_EFFECT_DURATION = 2.0

# 狀態效果強度
SLOW_EFFECT_RATE = 0.5  # 減速至原本的50%
PARALYSIS_EFFECT_RATE = 0.0  # 麻痺時完全無法移動

######################關卡環境設定######################

# 平台設定
PLATFORM_HEIGHT = 30
PLATFORM_COLOR = GRAY

# 陷阱設定
LAVA_TRAP_COLOR = RED
WATER_TRAP_COLOR = BLUE
WIND_TRAP_COLOR = WHITE
TRAP_DAMAGE = 20

# 火山場景
VOLCANO_BG_COLOR = (139, 69, 19)  # 褐色背景
LAVA_COLOR = (255, 69, 0)  # 亮橘紅色

# 海底場景
OCEAN_BG_COLOR = (0, 105, 148)  # 深藍色背景
BUBBLE_COLOR = (173, 216, 230)  # 淺藍色

# 颶風場景
STORM_BG_COLOR = (105, 105, 105)  # 暗灰色背景
WIND_COLOR = (220, 220, 220)  # 亮灰色

######################介面設定######################

# 血量條設定
HEALTH_BAR_WIDTH = 200
HEALTH_BAR_HEIGHT = 20
HEALTH_BAR_COLOR = GREEN
HEALTH_BAR_BG_COLOR = RED

# 子彈切換介面
BULLET_UI_SIZE = 40
BULLET_UI_SPACING = 50
BULLET_UI_Y = 50

# 分數顯示
SCORE_FONT_SIZE = 36
SCORE_COLOR = WHITE
